#!/usr/bin/env python3
from __future__ import annotations

from bootstrap import REFS_LOCK, head_sha, load_manifest, log, repo_dir


def main() -> int:
    specs = sorted(load_manifest(), key=lambda spec: spec.name)

    lines = ["# Generated by tools/update_refs.py", "# Format: <repo> <head_sha>"]
    for spec in specs:
        sha = head_sha(repo_dir(spec))
        lines.append(f"{spec.name} {sha}")

    REFS_LOCK.parent.mkdir(parents=True, exist_ok=True)
    REFS_LOCK.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"Wrote refs lockfile: {REFS_LOCK}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
